import { Router } from "express";
import healthRoutes from "./health.routes.js";
import publicRoutes from "./public.routes.js";
import authRoutes from "./auth.routes.js";
import companyRoutes from "./company.routes.js";
import userRoutes from "./user.routes.js";
import roleRoutes from "./role.routes.js";
import frameworkRoutes from "./framework.routes.js";
import applicationSettingsRoutes from "./applicationSettings.routes.js";
import locationRoutes from "./location.routes.js";
import subLocationRoutes from "./subLocation.routes.js";
import masterDataRoutes from "./masterData.routes.js";
import notificationRoutes from "./notification.routes.js";
import emailConfigRoutes from "./emailConfig.routes.js";
import auditLogRoutes from "./auditLog.routes.js";
import csvImportRoutes from "./csvImport.routes.js";
import fileUploadRoutes from "./fileUpload.routes.js";
import hsnPMasterRoutes from "./hsnPMaster.routes.js";
import sacPMasterRoutes from "./sacPMaster.routes.js";
import supplierMasterRoutes from "./supplierMaster.routes.js";
import prospectSupplierMasterRoutes from "./prospectSupplierMaster.routes.js";
import logisticsMasterRoutes from "./logisticsMaster.routes.js";
import serviceMasterRoutes from "./serviceMaster.routes.js";
import serviceMasterR1Routes from "./serviceMasterR1.routes.js";
import itemMasterRoutes from "./itemMaster.routes.js";
import itemInventoryLevelRoutes from "./itemInventoryLevel.routes.js";
import itemSupplierLinkRoutes from "./itemSupplierLink.routes.js";
import itemDocumentTypeRoutes from "./itemDocumentType.routes.js";
import itemAttributeDefinitionRoutes from "./itemAttributeDefinition.routes.js";
import assetMasterRoutes from "./assetMaster.routes.js";
import autoIncrementRoutes from "./autoIncrement.routes.js";
import dashboardRoutes from "./dashboard.routes.js";
import paymentTermsMasterRoutes from "./paymentTermsMaster.routes.js";
import sourceListMasterRoutes from "./sourceListMaster.routes.js";
import vendorEvaluationMasterRoutes from "./vendorEvaluationMaster.routes.js";
import vendorEvaluationShowcaseRoutes from "./vendorEvaluationShowcase.routes.js";
import qualityRoutes from "./quality.routes.js";
import inventoryStoreRoutes from "./inventoryStore.routes.js";
import locationSessionRoutes from "./locationSession.routes.js";
import purchaseTransactionRoutes from "./purchaseTransaction.routes.js";
import stockTransferRoutes from "./stockTransfer.routes.js";
import locationAuditRoutes from "./locationAudit.routes.js";
import path from "path";
import express from "express";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const uploadsDir = path.join(__dirname, "../../uploads");

const router = Router();

router.use("/health", healthRoutes);
router.use("/public", publicRoutes);
router.use("/auth", authRoutes);
router.use("/company", companyRoutes);
router.use("/users", userRoutes);
router.use("/roles", roleRoutes);
router.use("/framework", frameworkRoutes);
router.use("/company/application", applicationSettingsRoutes);
router.use("/locations", locationRoutes);
router.use("/location-session", locationSessionRoutes);
router.use("/sub-locations", subLocationRoutes);
router.use("/inventory-stores", inventoryStoreRoutes);
router.use("/purchase", purchaseTransactionRoutes);
router.use("/stock-transfers", stockTransferRoutes);
router.use("/location-audit", locationAuditRoutes);
router.use("/master-data", masterDataRoutes);
router.use("/notifications", notificationRoutes);
router.use("/email", emailConfigRoutes);
router.use("/audit-logs", auditLogRoutes);
router.use("/csv-import", csvImportRoutes);
router.use("/files", fileUploadRoutes);
router.use("/hsn-p-master", hsnPMasterRoutes);
router.use("/sac-p-master", sacPMasterRoutes);
router.use("/supplier-master", supplierMasterRoutes);
router.use("/prospect-supplier-master", prospectSupplierMasterRoutes);
router.use("/logistics-master", logisticsMasterRoutes);
router.use("/service-master", serviceMasterRoutes);
router.use("/service-master-r1", serviceMasterR1Routes);
router.use("/item-document-types", itemDocumentTypeRoutes);
router.use("/item-attribute-definitions", itemAttributeDefinitionRoutes);
router.use("/item-master", itemMasterRoutes);
router.use("/item-master", itemSupplierLinkRoutes);
router.use("/item-inventory-levels", itemInventoryLevelRoutes);
router.use("/asset-master", assetMasterRoutes);
router.use("/auto-increment", autoIncrementRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/payment-terms-master", paymentTermsMasterRoutes);
router.use("/source-list-master", sourceListMasterRoutes);
router.use("/vendor-evaluation-master", vendorEvaluationMasterRoutes);
router.use("/vendor-evaluation-showcase", vendorEvaluationShowcaseRoutes);
router.use("/quality", qualityRoutes);
router.use("/uploads", express.static(uploadsDir));

export default router;
