/** Maps parent menu codes to sub-modules for access management UI. */
export const SUBMODULES_MAP = {
  menu_1: [],
  menu_2: [],
  menu_3: [],
  menu_4: [],
  menu_5: [],
  menu_6: [],
  menu_7: [],
  menu_8: [],
  sales: [
    { id: "sales_gst_s", label: "GST/S" },
    { id: "sales_service_master", label: "Service Master" },
    { id: "sales_b2b_customer", label: "B2B Customer" },
    { id: "sales_sku", label: "SKU" },
    { id: "sales_sku_customer_interface", label: "SKU-Customer Interface" },
    { id: "sales_logistics", label: "Logistics" },
    { id: "sales_customer_open_po", label: "Customer Open PO" },
    { id: "sales_product_master", label: "Product Master" },
  ],
  masters: [
    { id: "masters_leads_npd", label: "Leads & NPD" },
    { id: "masters_planning", label: "Planning" },
    { id: "masters_sales", label: "Sales" },
    { id: "masters_purchase", label: "Purchase" },
    { id: "masters_stores", label: "Stores" },
    { id: "masters_production", label: "Production" },
    { id: "masters_maintenance", label: "Maintenance" },
    { id: "masters_quality", label: "Quality" },
    { id: "masters_dispatch", label: "Dispatch" },
    { id: "masters_hrm", label: "HR" },
    { id: "masters_accounts", label: "Accounts" },
    { id: "masters_finance", label: "Finance" },
  ],
  settings: [
    { id: "company_setup_group", label: "Company Setup" },
    { id: "app_setup_group", label: "Application Setup" },
    { id: "roles_access", label: "Roles & Access" },
    { id: "data_mgmt_group", label: "Data Management" },
    { id: "communication_group", label: "Communication" },
    { id: "system_group", label: "System" },
    { id: "permission_management", label: "Permission Management" },
    { id: "application_setup", label: "Application Set-up" },
    { id: "groups_setup", label: "Groups Setup" },
    { id: "icons_setup", label: "Menu Icons" },
    { id: "menu_setup", label: "Menu Setup" },
    { id: "modules_setup", label: "Modules Setup" },
    { id: "company_setup", label: "Company" },
    { id: "location_master", label: "Location Master" },
    { id: "sub_locations", label: "Sub-locations" },
    { id: "master_data", label: "Master Data" },
    { id: "email_setup", label: "Email Configuration" },
    { id: "audit_logs", label: "Audit Logs" },
    { id: "active_users", label: "Active Users" },
    { id: "bulk_import", label: "Bulk CSV Import" },
    { id: "file_manager", label: "File Manager" },
  ],
};
